### ISSUE TITLE
Token to string?

### ISSUE THREAD

**Issue by ninjatill** [rickkas7/JsonParserGeneratorRK#2]
Is there a way to send the inner content of a token to a string without parsing it first and then running it back through a generator? Here is the scenario I am working on. Consider this JSON string:

`{"Q":[{"M":{"M":11,"U":2000,"T":2}}, {"M":{"M":2,"U":6000,"T":6,"C":[0,255,0,16543],"A":1}} ] }`

The outer "Q" (sequence) array is an array of "M" (mode) commands. When I am parsing the sequence, I want to take each inner mode command and store it as a raw Json string (to include the enclosing braces). I create a sequence object in memory which contains a vector of Strings. When running my program and advancing through the vector, I take the stored, raw JSON string and parse the "M" commands on the fly. So while initially parsing the "Q" array, I would like to take each inner "M" object as a string: i.e. "{"M":{"M":11,"U":2000,"T":2}}" and store it in my vector of strings.

One reason for storing the element as a raw Json string is that the command could be of another type such as a settings update ("S" command) or a repeater element ("R" command... tells the program to repeat the last x elements.)

When using the ported SparkJson, my code looked like this:

```C++
void ParseSequence(JsonArray &seqArray, Sequencer &seqToUpdate, bool Add) {
    Sequencer sq;
    
    Log.info("...Elements in sequence: %i", seqArray.size());
    char value[255];
    for (int i=0; i<seqArray.size(); i++) {
        JsonObject& j = seqArray[i].as<JsonObject&>();
        j.printTo(value, 255);  //Outputs the inner Json object to a char array.
        if (value.success()) {
            Log.trace("...Element Index: %i, Payload: %s", i, value);
            if (!Add) {  //Replace the sequence or add to it?
                sq.Add(value);
            } else {
                seqToUpdate.Add(value);
            }
        }
    }
    
    if (!Add) {
        Log.info("...Replacing sequence.");
        seqToUpdate = sq;
    }
    
    Log.trace(seqToUpdate.ToString());
}
```

Using this library, is there an equivalent way to take a given token and output it as a string to include the enclosing braces?

Could I do something like...?:
```C++
char *strValue;
jsmntok_t *token;
int dataLen = (token->start) - (token->end);
memcpy(strvalue, jparser.&buffer[token->start], dataLen);
```

**Comment by rickkas7** [comment]
A added two new functions in version 0.0.5 of the library to get the JSON back after parsing:

```
	/**
	 * Converts a token (object, array, string, or primitive) back into JSON
	 */
	bool getTokenJsonString(const JsonParserGeneratorRK::jsmntok_t *token, String &result) const;

	/**
	 * Converts a token (object, array, string, or primitive) back into JSON
	 */
	bool getTokenJsonString(const JsonParserGeneratorRK::jsmntok_t *token, char *str, size_t &strLen) const;
```
