### ISSUE TITLE
Parser not returning data

### ISSUE THREAD

**Issue by proffalken** [rickkas7/JsonParserGeneratorRK#3]
Hey, I'm new to this library, and I think I'm holding it wrong...

I have JSON returned from a webhook targeting https://postcodes.io/ which looks like this:

```
{
  "latitude": 51.827172,
  "longitude": -2.718521,
  "returned_postcode": "AA00 0AA"
}
```

I'm trying to process this with the following code:

```
void configureGpsLocation(const char *event, const char *data){
   
    Particle.publish("received_data", data);
    parser.addString(data);
    if (parser.parse()){
      Particle.publish("success","JSON Data Parsed Successfully");
      String returned_postcode = parser.getReference().key("returned_postcode").valueString();
      float lat = parser.getReference().key("latitude").valueFloat();
      float lng = parser.getReference().key("longitude").valueFloat();
      Particle.publish("returned_postcode", returned_postcode);
      Particle.publish("target_latitude", String(lat));
      Particle.publish("target_longitude", String(lng));
    } else {
        Particle.publish("error","could not parse json");
    }
}
```
but all of the values published to the console return either `null` in the case of the postcode, or `0.000000` in the case of the lat/lng values.

The `parser.parse()` code always seems to evaluate as `true`, as I don't get to the `could not parse json` output.

**Comment by ScruffR** [comment]
You need to start with an *empty* `parser` to have this code work. 
Try calling `parser.clear()` to ensure you are actually looking at the correct data.

To test my hypothesis you can `Serial.println(parser.getBuffer());` and see what the JSON buffer actually contains *before* you try parsing.

**Comment by rickkas7** [comment]
I believe the problem is this:

> NOTE 2: Particle.publish() and the Particle.subscribe()handler(s) share the same buffer. As such, calling Particle.publish() within a Particle.subscribe() handler will wipe the subscribe buffer! In these cases, copying the subscribe buffer's content to a separate char buffer prior to calling Particle.publish() is recommended.
https://docs.particle.io/reference/device-os/firmware/photon/#particle-subscribe-

When you Particle.publish from a subscribe handler you overwrite the contents of the received data, which is why you can't read the latitude, etc. successfully.

**Comment by proffalken** [comment]
I can confirm that this was the case.  Switching the subscribe and the publish around worked a treat.

Thanks :)
