### ISSUE TITLE
parse() returns true after using addString() with empty char array

### ISSUE THREAD

**Issue by nrobinson2000** [rickkas7/JsonParserGeneratorRK#7]
Escalated from: https://community.particle.io/t/send-json-from-cloud-to-photon/28636/19?u=nrobinson2000

If I call the cloud function without supplying any arguments (`particle call argon jsonBug`) I witness the same behavior described in the post. I ran the code on an Argon and used the debugger to step through the `addString()` and `parse()` methods.

The bug appears to be on [line 133 of JsonParserGeneratorRK.cpp](https://github.com/rickkas7/JsonParserGeneratorRK/blob/master/src/JsonParserGeneratorRK.cpp#L133)
```cpp
		if (result < 0) {
			// Failed to parse: JSMN_ERROR_INVAL or JSMN_ERROR_PART
			return false;
		}
```

When debugging I found that `result` was equal to zero.

Is there a reason why zero is considered valid? Or should line 133 be changed to fix this behavior?

```cpp
		if (result <= 0) {
```

## TEST CODE
```cpp
#include "Particle.h"
#include "JsonParserGeneratorRK.h"

JsonParserStatic<1024, 30> parser1;

int jsonBug(const char *args)
{
    Serial.printlnf("args = %s", args);
        
    parser1.clear();
    parser1.addString(args);

    if (parser1.parse())
    {
        int onH = 0;
        parser1.getOuterValueByKey("onH", onH);
        Serial.printlnf("onHour = %d", onH);

        int onM = 0;
        parser1.getOuterValueByKey("onM", onM);
        Serial.printlnf("onMinute = %d", onM);

        int offH = 0;
        parser1.getOuterValueByKey("offH", offH);
        Serial.printlnf("offHour = %d", offH);

        int offM = 0;
        parser1.getOuterValueByKey("offM", offM);
        Serial.printlnf("offMinute = %d", offM);
        Serial.println();
        return 0;
    }

    Serial.println("Could not parse JSON!");
    Serial.println();
    return 1;
}

// TESTS
// particle call argon jsonBug '{"onH":1,"onM":35,"offH":2,"offM":55}'
// particle call argon jsonBug 'hello world'
// particle call argon jsonBug
// particle call argon jsonBug ''

void setup()
{
    Serial.begin(115200);
    Particle.function("jsonBug", jsonBug);
}

void loop()
{
}
```

**Comment by rickkas7** [comment]
That looks like a bug, but I would just short-circuit the whole thing with a check at the top of parse(). If offset == 0, return false. I'll make that change.

**Comment by rickkas7** [comment]
Version 0.1.1 released with the fix
- Fixed a bug where calling parse() on an empty buffer returns true. It should return false.
